"use client";

import {
  createContext,
  useContext,
  useMemo,
  useSyncExternalStore,
} from "react";

const STORAGE_KEY = "rafi-picture-language";
const DEFAULT_LANGUAGE = "id";

const translations = {
  id: {
    home: "Beranda",
    portfolio: "Portofolio",
    packages: "Paket",
    booking: "Pemesanan",
    login: "Masuk",
    myAccount: "Akun Saya",
    language: "Bahasa",
    english: "English",
    indonesian: "Bahasa Indonesia",
    nextStep: "Langkah Berikutnya",
    previous: "Sebelumnya",
    heroTitle: "Mengabadikan Momen, Menciptakan Kenangan",
    heroDescription:
      "Setiap momen memiliki cerita, kami mengabadikannya dengan sentuhan profesional dan penuh keindahan.",
    viewPackages: "Lihat Paket",
    bookNow: "Pesan Sekarang",
    whyChooseUs: "Mengapa Memilih Rafi Picture?",
    qualityPhotos: "HASIL FOTO BERKUALITAS",
    qualityPhotosDescription:
      "Menghasilkan foto dengan detail yang tajam, komposisi yang tepat, dan warna yang natural.",
    professionalEditing: "EDITING PROFESIONAL",
    professionalEditingDescription:
      "Setiap foto melalui proses editing untuk menghasilkan tampilan yang clean, estetik, dan konsisten.",
    professionalService: "PELAYANAN PROFESIONAL",
    professionalServiceDescription:
      "Didukung fotografer berpengalaman dengan proses kerja yang terencana dan sesuai kebutuhan setiap klien.",
    footerDescription:
      "Dokumentasi fotografi untuk wedding, prewedding, engagement, dan berbagai momen spesial dengan hasil yang natural, estetik, dan berkarakter.",
    contactMessage:
      "Halo Rafi Picture, saya ingin bertanya mengenai layanan Rafi Picture.",
    navigation: "Navigasi",
    contactUs: "Hubungi Kami",
    connect: "Terhubung",
    information: "Informasi",
    terms: "Syarat & Ketentuan",
    termsDescription:
      "Ketentuan booking, pembayaran, durasi layanan, dan kebijakan layanan Rafi Picture.",
    copyright: "Hak cipta dilindungi.",
    welcomeBack: "Selamat Datang Kembali",
    authLoginDescription:
      "Masuk untuk mengakses galeri pribadi dan mengelola pemesanan Anda.",
    joinStudio: "Bergabung dengan Studio",
    authRegisterDescription:
      "Buat akun dan simpan setiap momen Rafi Picture di satu tempat.",
    signIn: "Masuk",
    createAccount: "Buat Akun",
    emailAddress: "Alamat Email",
    password: "Kata Sandi",
    forgotPassword: "Lupa Kata Sandi?",
    keepSignedIn: "Tetap masuk",
    signingIn: "Sedang Masuk...",
    firstName: "Nama Depan",
    lastName: "Nama Belakang",
    createPassword: "Buat Kata Sandi",
    confirmPassword: "Konfirmasi Kata Sandi",
    sendingVerification: "Mengirim Kode Verifikasi...",
    firstNameLastNameRequired: "Nama depan dan nama belakang wajib diisi.",
    emailRequired: "Alamat email wajib diisi.",
    passwordMinLength: "Kata sandi harus memiliki minimal 8 karakter.",
    passwordMismatch: "Kata sandi tidak cocok.",
    verificationFailed: "Gagal mengirim kode verifikasi.",
    orContinueWith: "Atau lanjutkan dengan",
    firstNamePlaceholder: "Budi",
    lastNamePlaceholder: "Santoso",
    passwordPlaceholder: "Min. 8 karakter",
    repeatPasswordPlaceholder: "Ulangi kata sandi",
    emailPlaceholder: "nama@email.com",
    packageFallbackDescription:
      "Paket fotografi yang dapat disesuaikan dengan kebutuhan acara Anda.",
    packagesPageTitle: "Paket Fotografi Kami",
    packagesPageDescription:
      "Mengabadikan momen abadi dalam hidup Anda melalui lensa editorial. Pilih paket yang sesuai dengan visi Anda.",
    portfolioPageLabel: "Portofolio",
    portfolioPageTitle: "Cerita yang Kami Abadikan",
    portfolioPageDescription:
      "Kumpulan momen pilihan dari Rafi Picture. Setiap kunjungan menampilkan susunan foto secara acak dari galeri portofolio.",
    bookingPageTitle: "Pesan Sesi Anda",
    bookingPageDescription:
      "Abadikan momen yang menjadi bagian penting dalam babak terbesar hidup Anda.",
    validPackageRequired: "Silakan pilih paket yang valid.",
    bookingSubmitFailed: "Booking gagal dikirim. Silakan coba kembali.",
    bookingDataUnavailable: "Data booking tidak tersedia.",
    paymentBookingMismatch: "Booking pembayaran tidak sesuai.",
    paymentInvoiceUnavailable: "Invoice pembayaran tidak sesuai atau sudah tidak aktif.",
    depositInvoiceUnavailable: "Invoice DP belum tersedia.",
    finalInvoiceUnavailable: "Invoice pelunasan belum tersedia.",
    paymentHandlerUnavailable: "Handler pengiriman pembayaran belum tersedia.",
    paymentProofRequired: "Pilih bukti pembayaran terlebih dahulu.",
    paymentProofUploadFailed: "Bukti pembayaran gagal dikirim. Silakan coba kembali.",
    viewDetail: "Lihat Detail",
    noPackages: "Belum ada paket tersedia",
    popular: "Paling Populer",
    packageLabel: "Paket",
    startingFrom: "Mulai dari",
    investmentStartingFrom: "Investasi Mulai Dari",
    includedInPackage: "Termasuk dalam Paket",
    reserveDate: "Reservasi Tanggal Anda",
    coverage: "Liputan",
    close: "Tutup",
    termsTitle: "Ketentuan Layanan",
    termsVersion: "Versi Ketentuan",
    termsName: "Ketentuan Layanan Rafi Picture",
    noPackagesDescription: "Paket aktif pada kategori ini akan muncul secara otomatis.",
    stepPackages: "Paket",
    stepEventInfo: "Info Acara",
    stepPersonalDetails: "Data Pribadi",
    stepConfirm: "Konfirmasi",
    yourPackagePlan: "Rencana Paket Anda",
    choosePackageDescription: "Pilih paket dokumentasi yang sesuai dengan jenis acara dan kebutuhan Anda.",
    selected: "Dipilih",
    mostPopular: "Paling Populer",
    selectedPackage: "Paket pilihan Anda",
    changePackage: "Ganti Paket",
    choosePackage: "Pilih Paket",
    noPackageSelected: "Belum ada paket yang dipilih",
    choosePackageDescriptionShort: "Lihat daftar paket berdasarkan kategori, harga, durasi, dan layanan yang tersedia.",
    packageUnavailable: "Paket dari URL tidak ditemukan atau sudah tidak aktif. Silakan pilih paket lainnya.",
    personalInformation: "Informasi Pribadi",
    customerData: "Data Pemesan",
    personalDescription: "Isi data yang dapat dihubungi oleh tim Rafi Picture terkait booking dan kebutuhan acara.",
    fullName: "Nama Lengkap",
    fullNamePlaceholder: "Nama lengkap",
    partnerName: "Nama Pasangan",
    partnerNamePlaceholder: "Nama pasangan",
    phoneNumber: "Nomor Telepon",
    phonePlaceholder: "08xxxxxxxxxx",
    optional: "Opsional",
    additionalNotes: "Catatan Tambahan",
    tellVision: "Ceritakan Visi Anda",
    visionDescription: "Ceritakan konsep, suasana, atau kebutuhan khusus yang kamu inginkan. Bagian ini opsional.",
    visionPlaceholder: "Contoh: konsep intimate, tone hangat, fokus candid keluarga...",
    useMyData: "Pakai Data Saya",
    next: "Berikutnya",
    previousStep: "Sebelumnya",
    fullNameRequired: "Nama lengkap wajib diisi.",
    fullNameMinLength: "Nama lengkap harus memiliki minimal 2 karakter.",
    validEmail: "Masukkan alamat email yang valid.",
    phoneRequired: "Nomor telepon wajib diisi.",
    validPhone: "Masukkan nomor telepon yang valid.",
    eventDateRequired: "Tanggal acara wajib diisi.",
    eventDatePast: "Tanggal acara tidak boleh di masa lalu.",
    startTimeRequired: "Jam mulai acara wajib dipilih.",
    venueRequired: "Venue atau lokasi acara wajib diisi.",
    mapLocationRequired: "Pilih titik lokasi acara pada peta.",
    packageRequired: "Silakan pilih paket.",
    packageUnavailableError: "Paket yang dipilih sudah tidak tersedia.",
    packageLoadError: "Paket tidak dapat dimuat. Silakan coba kembali.",
    hoursCoverage: "jam liputan",
    selectedPackages: "Paket Terpilih",
    addAnotherPackage: "Tambah Paket",
    removePackage: "Hapus Paket",
    categoryLoadError: "Kategori tidak dapat dimuat. Semua paket masih dapat dipilih.",
    showing: "Menampilkan",
    eventInformation: "Informasi Acara",
    schedule: "Jadwal",
    dateTime: "Tanggal & Waktu",
    chooseDateDescription: "Pilih tanggal acara terlebih dahulu. Setelah tanggal dipilih, tentukan jam mulai acara.",
    eventDate: "Tanggal Acara",
    notSelected: "Belum dipilih",
    changeDate: "Ubah Tanggal",
    chooseDate: "Pilih Tanggal",
    dateAvailable: "Tanggal tersedia dan sudah dipilih.",
    scheduleLoadError: "Data jadwal gagal dimuat. Silakan coba kembali.",
    startTime: "Jam Mulai",
    endTime: "Selesai",
    nextDay: "hari berikutnya",
    chooseStartTime: "Pilih jam mulai",
    packageDurationUnavailable: "Durasi paket belum tersedia",
    packageDuration: "Durasi paket",
    endTimeDescription: "Jam selesai akan dihitung setelah durasi paket tersedia.",
    venue: "Venue",
    eventLocation: "Lokasi Acara",
    locationDescription: "Isi nama venue atau alamat. Tombol Cari Lokasi bersifat opsional, kamu juga bisa memilih titik langsung pada peta.",
    venueAddress: "Nama Venue / Alamat",
    venuePlaceholder: "Contoh: Hotel Savoy Homann Bandung",
    searching: "Mencari...",
    searchLocation: "Cari Lokasi",
    locationHelp: "Nama venue boleh berupa nama bebas. Yang wajib adalah nama lokasi terisi dan titik pada peta sudah dipilih.",
    locationFound: "Lokasi ditemukan. Titik peta sudah disesuaikan.",
    mapPoint: "Titik Peta",
    useMyLocation: "Gunakan lokasi saya",
    removePoint: "Hapus titik",
    waitingLocation: "Menunggu lokasi",
    agencyNotConfigured: "Agency belum dikonfigurasi",
    distanceFrom: "Jarak dari",
    accommodationCost: "Biaya Akomodasi",
    accommodationRequest: "Request Akomodasi",
    accommodationPolicyShort: "Untuk seluruh area kota Bandung Free Akomodasi, diluar itu akan dikenakan biaya.",
    bandungAccommodation: "Seluruh area Kota Bandung bebas biaya akomodasi. Untuk lokasi di luar Kota Bandung dikenakan biaya akomodasi.",
    freeDistance: "Jarak gratis berlaku hingga",
    afterDistance: "; setelah itu dikenakan",
    andIncreases: "dan bertambah",
    eachDistance: "untuk setiap kelipatan",
    distanceStraightLine: "berikutnya. Jarak dihitung secara garis lurus.",
    confirmation: "Konfirmasi",
    reviewBooking: "Periksa Kembali Booking Anda",
    reviewBookingDescription: "Pastikan detail paket, jadwal, lokasi, dan informasi kontak sudah sesuai sebelum permintaan booking dikirim.",
    beforeSubmitBooking: "Sebelum Mengirim Booking",
    beforeSubmitAvailability: "Pengiriman formulir belum menjamin ketersediaan tanggal acara.",
    beforeSubmitReview: "Tim akan meninjau jadwal, lokasi, dan kebutuhan acara terlebih dahulu.",
    beforeSubmitPrice: "Harga paket dapat berubah jika terdapat kebutuhan tambahan.",
    beforeSubmitContact: "Tim akan menghubungi Anda melalui email atau nomor telepon yang dicantumkan.",
    submittingBooking: "Mengirim permintaan booking...",
    bookingSentSuccess: "Permintaan booking berhasil dikirim.",
    bookingWillBeReviewed: "Data telah diterima dan akan ditinjau oleh tim.",
    packageDetails: "Paket Dokumentasi",
    selectedPackageDescription: "Paket dan layanan yang dipilih untuk acara ini.",
    includedServices: "Layanan Termasuk",
    packagePrice: "Harga Paket",
    subjectCouple: "Couple / berpasangan",
    subjectIndividual: "Individual",
    subjectUnknown: "Jenis subjek belum dikategorikan",
    eventDetails: "Detail Acara",
    eventDetailsDescription: "Jadwal, lokasi, dan biaya akomodasi untuk booking ini.",
    eventTime: "Jam Acara",
    personalDetails: "Data Pemesan",
    personalDetailsDescription: "Informasi yang digunakan tim untuk menghubungi Anda.",
    visionNotes: "Visi & Catatan",
    visionNotesDescription: "Konsep atau kebutuhan tambahan yang ingin disampaikan kepada tim.",
    eventNotes: "Catatan Acara",
    accommodationPolicy: "Seluruh area Kota Bandung bebas biaya akomodasi. Untuk lokasi di luar Kota Bandung dikenakan biaya akomodasi. Jarak gratis berlaku hingga",
    all: "Semua",
    categoryWedding: "Pernikahan",
    categoryPreWedding: "Pra-Pernikahan",
    categoryEngagement: "Pertunangan",
    categoryEvent: "Acara",
    categoryBundle: "Bundel",
    bookingDataUnavailable: "Data booking tidak tersedia.",
    statusPendingLabel: "Menunggu Review",
    statusPendingTitle: "Permintaan Booking Berhasil Dikirim",
    statusPendingDescription: "Permintaan booking Anda sudah diterima. Tim Rafi Picture akan meninjau jadwal, lokasi, paket, dan kebutuhan acara terlebih dahulu.",
    statusApprovedLabel: "Disetujui",
    statusApprovedTitle: "Booking Disetujui",
    statusApprovedDescription: "Permintaan booking Anda sudah disetujui. Silakan lanjutkan ke tahap pembayaran deposit.",
    statusConfirmedLabel: "Pembayaran Dikirim",
    statusConfirmedTitle: "Pembayaran Sedang Ditinjau",
    statusConfirmedDescription: "Bukti pembayaran sudah diterima dan sedang diverifikasi oleh admin Rafi Picture.",
    statusInProgressLabel: "Dalam Proses",
    statusInProgressTitle: "Booking Sedang Berjalan",
    statusInProgressDescription: "Booking Anda sudah aktif dan tim sedang mempersiapkan layanan sesuai detail acara.",
    statusCompletedLabel: "Selesai",
    statusCompletedTitle: "Booking Selesai",
    statusCompletedDescription: "Seluruh proses booking telah selesai. Terima kasih telah menggunakan layanan Rafi Picture.",
    statusCancelledLabel: "Dibatalkan",
    statusCancelledTitle: "Booking Dibatalkan",
    statusCancelledDescription: "Booking ini telah dibatalkan. Hubungi tim Rafi Picture jika Anda membutuhkan informasi lebih lanjut.",
    statusFinalPaymentLabel: "Pelunasan Dikirim",
    statusFinalPaymentTitle: "Pelunasan Sedang Ditinjau",
    statusFinalPaymentDescription: "Bukti pembayaran pelunasan sudah diterima dan sedang diverifikasi oleh admin Rafi Picture.",
    statusPaidLabel: "Lunas",
    statusPaidTitle: "Pembayaran Sudah Lunas",
    statusPaidDescription: "Seluruh pembayaran booking sudah terverifikasi. Invoice dan kuitansi pembayaran tersedia pada bagian Dokumen Pembayaran.",
    serviceStatus: "Status layanan: Dalam Proses",
    bookingCode: "Kode Booking",
    submittedAt: "Dikirim",
    travelCost: "Biaya Perjalanan",
    eventDateLabel: "Tanggal Acara",
    eventLocationLabel: "Lokasi Acara",
    clientDataDescription: "Informasi kontak yang digunakan tim Rafi Picture untuk komunikasi booking.",
    visionAndNotes: "Visi & Catatan",
    visionAndNotesDescription: "Konsep atau kebutuhan tambahan yang disampaikan saat booking.",
    costSummary: "Ringkasan Biaya",
    costSummaryDescription: "Ringkasan ini berdasarkan paket dan biaya perjalanan pada saat permintaan booking dikirim.",
    sendingBooking: "Mengirim...",
    inquirySent: "Permintaan Terkirim",
    sendInquiry: "Kirim Permintaan",
    paymentDocuments: "Dokumen Pembayaran",
    paymentDocumentsDescription: "Invoice dan kuitansi yang sudah diterbitkan untuk booking ini.",
    finalAmountNotice: "Nominal final akan mengikuti hasil review admin dan invoice yang diterbitkan setelah booking disetujui.",
    lastUpdated: "Terakhir diperbarui",
    nextDay: "hari berikutnya",
    depositInvoice: "Invoice DP",
    finalInvoice: "Invoice Pelunasan",
    paymentReceipt: "Kuitansi Pembayaran",
    fullPayment: "Pembayaran 100%",
    adminDashboard: "Dashboard",
    adminSchedules: "Jadwal",
    adminCrewManagement: "Manajemen Kru",
    adminOrders: "Pesanan",
    adminPackageManagement: "Manajemen Paket",
    adminPayments: "Pembayaran",
    adminStudio: "Admin Studio",
    changePhoto: "Ubah Foto",
    loggingOut: "Keluar...",
    logout: "Keluar",
    expandSidebar: "Buka sidebar",
    collapseSidebar: "Tutup sidebar",
    adminOverview: "Ringkasan",
    dashboard: "Dashboard",
    dashboardDescription: "Ringkasan langsung dari booking, jadwal kru, dan pembayaran.",
    totalOrders: "Total Pesanan",
    upcomingSchedules: "Jadwal Mendatang",
    monthlyRevenue: "Pendapatan Bulanan",
    pendingPayments: "Pembayaran Tertunda",
    verified: "Terverifikasi",
    pending: "Tertunda",
    failedToLoadDashboard: "Dashboard gagal dimuat",
    dashboardDataUnavailable: "Data booking, penugasan, atau pembayaran tidak dapat dimuat.",
    report: "Laporan",
    bookingReport: "Laporan Booking",
    reportPeriod: "Periode Laporan",
    downloadReport: "Unduh Laporan",
    totalRevenue: "Total Pendapatan",
    totalClients: "Total Klien",
    mostSelectedPackage: "Paket Paling Dipilih",
    selections: "Jumlah Dipilih",
    package: "Paket",
    monthlyBookings: "Booking Bulanan",
    monthlyBookingsDescription: "Permintaan booking yang dikirim selama enam bulan terakhir.",
    lastMonths: "6 bulan terakhir",
    paymentDistribution: "Distribusi Pembayaran",
    paymentDistributionDescription: "Pembayaran terverifikasi dan tertunda bulan ini.",
    fulfilled: "Terpenuhi",
    latestBookings: "Booking Terbaru",
    latestBookingsDescription: "Permintaan booking yang paling baru dikirim.",
    viewAll: "Lihat Semua",
    noBookingsYet: "Belum Ada Booking",
    newBookingsAppear: "Permintaan booking baru akan muncul di sini setelah klien mengirim formulir booking.",
    billingAndPayments: "Penagihan & Pembayaran",
    manageYourPayment: "Kelola Pembayaran Anda",
    completeDepositUpload: "Selesaikan pembayaran DP dan unggah bukti transfer untuk melanjutkan booking.",
    completeFinalUpload: "Selesaikan pembayaran pelunasan dan unggah bukti transfer untuk menyelesaikan kewajiban pembayaran booking.",
    paymentStatus: "Status",
    transactionSuccessful: "Berhasil",
    awaitingPayment: "Menunggu Pembayaran",
    awaitingVerification: "Menunggu Verifikasi",
    paymentVerified: "Pembayaran Terverifikasi",
    paymentComplete: "Selesai",
    cancelledStatus: "Dibatalkan",
    finalPaymentWaiting: "Menunggu Pelunasan",
    transactionHistory: "Riwayat Transaksi",
    noTransactions: "Belum ada transaksi",
    transactionHistoryEmpty: "Riwayat pembayaran akan muncul setelah bukti transfer dikirim.",
    reference: "Referensi",
    method: "Metode",
    quantity: "Jumlah",
    remainingDue: "Sisa yang Harus Dibayar",
    downloadReceipt: "Unduh Kuitansi",
    bankTransfer: "Transfer Bank",
    copied: "Tersalin",
    copy: "Salin",
    paymentProofSent: "Bukti Pembayaran Terkirim",
    paymentProofReview: "Admin sedang meninjau bukti transfer Anda. Form upload akan tersedia kembali apabila pembayaran ditolak.",
    uploadUnavailable: "Upload Tidak Tersedia",
    uploadOnlyApproved: "Bukti transfer hanya dapat dikirim ketika status booking sudah disetujui.",
    paymentProof: "Bukti Pembayaran",
    days: "Hari",
    hours: "Jam",
    minutes: "Menit",
    seconds: "Detik",
    towardEventDay: "Menuju Hari Acara",
    eventDayArrived: "Hari acara telah tiba",
    eventCountdown: "Hitung mundur acara",
    live: "Live",
    eventStartReached: "Waktu mulai acara sudah tercapai. Detail status booking tetap mengikuti proses operasional Rafi Picture.",
    eventStarts: "Acara dimulai",
    timerFrozen: "Timer Dibekukan",
    overdue: "Terlambat",
    paymentDeadline: "Tenggat Pembayaran",
    previousProofRejected: "Bukti sebelumnya ditolak",
    adminDeadline: "Tenggat admin",
    issuedDate: "Tanggal Terbit",
    invoiceLabel: "Faktur",
    servicePackage: "Paket Layanan",
    totalCost: "Total Biaya",
    depositDue: "DP yang Harus Dibayar",
    finalPaymentDue: "Pelunasan yang Harus Dibayar",
    invoiceFile: "File Invoice",
    depositInvoiceLabel: "Invoice Down Payment",
    finalInvoiceLabel: "Invoice Pelunasan",
    viewPdf: "Lihat PDF",
    depositVerifiedNotice: "Booking akan diamankan setelah pembayaran DP diverifikasi oleh admin. Simpan bukti transfer sampai proses verifikasi selesai.",
    finalVerifiedNotice: "Setelah pelunasan diverifikasi, sistem akan menerbitkan kuitansi pembayaran 100% dan mengirimkannya melalui email.",
    paymentDeadlineDescription: "Selesaikan pembayaran dan kirim bukti transfer sebelum tenggat yang ditentukan admin.",
    uploadPaymentProof: "Unggah Bukti Pembayaran",
    clickOrDropUpload: "Klik untuk unggah atau seret dan lepas",
    imageRequirements: "PNG, JPG, atau JPEG - maksimal 5 MB",
    removeFile: "Hapus file",
    sendingPaymentProof: "Mengirim Bukti Pembayaran...",
    confirmPaymentProof: "Konfirmasi Bukti Pembayaran",
    selectProofToEnable: "Tombol konfirmasi aktif setelah foto bukti pembayaran dipilih.",
    copiedAccountError: "Nomor rekening gagal disalin.",
    frozenOverdueDescription: "Waktu keterlambatan dibekukan saat bukti pembayaran dikirim dan dilanjutkan dari posisi yang sama jika bukti ditolak admin.",
    frozenDescription: "Countdown dibekukan saat bukti pembayaran dikirim selama menunggu verifikasi admin.",
    overdueDescription: "Tenggat sudah terlewati. Timer keterlambatan terus berjalan sampai bukti pembayaran berikutnya dikirim.",
    timerFrozen: "Timer Dibekukan",
    previousProofRejected: "Bukti sebelumnya ditolak",
    adminDeadline: "Tenggat admin",
    bookings: "Booking",
    bookingManagement: "Manajemen Booking",
    bookingManagementDescription: "Tinjau permintaan booking, pantau status, dan kelola pesanan fotografi.",
    bookingSummary: "Ringkasan Booking",
    bookingFilters: "Filter Booking",
    searchClientPackageLocation: "Cari klien, paket, atau lokasi...",
    filterBookingStatus: "Filter status booking",
    allStatuses: "Semua Status",
    advancedFilters: "Filter lanjutan",
    downloadData: "Unduh data",
    client: "Klien",
    eventDate: "Tanggal Acara",
    amount: "Jumlah",
    status: "Status",
    action: "Aksi",
    pendingReview: "Menunggu Review",
    approvedAwaitingPayment: "Disetujui · Menunggu Pembayaran",
    paymentUnderReview: "Pembayaran Sedang Ditinjau",
    inProgress: "Dalam Proses",
    completed: "Selesai",
    cancelled: "Dibatalkan",
    paymentsPage: "Pembayaran",
    paymentManagement: "Manajemen Pembayaran",
    paymentManagementDescription: "Tinjau bukti pembayaran dan kelola status transaksi booking.",
    paymentFilters: "Filter pembayaran",
    searchPayment: "Cari pembayaran...",
    allPayments: "Semua Pembayaran",
    newestFirst: "Terbaru Terlebih Dahulu",
    oldestFirst: "Terlama Terlebih Dahulu",
    noPaymentsFound: "Tidak ada pembayaran",
    noPaymentsFoundDescription: "Pengajuan pembayaran klien akan muncul di sini setelah bukti pembayaran diunggah.",
    reviewPayment: "Tinjau pembayaran",
    verificationDetail: "Detail Verifikasi",
    rejected: "Ditolak",
    schedule: "Jadwal",
    scheduleManagement: "Manajemen Jadwal",
    scheduleManagementDescription: "Lihat permintaan booking yang menunggu review dan jadwal aktif setelah pembayaran DP diverifikasi.",
    loadingScheduleData: "Memuat data jadwal...",
    failedLoadScheduleData: "Data booking atau jadwal gagal dimuat.",
    showAll: "Tampilkan Semua",
    showBookings: "Tampilkan Pesanan",
    showSchedules: "Tampilkan Terjadwal",
    crew: "Kru",
    totalCrew: "Total Kru",
    available: "Tersedia",
    currentlyAssigned: "Sedang Ditugaskan",
    upcomingAssignments: "Penugasan Mendatang",
    packageManagement: "Manajemen Paket",
    packageManagementDescription: "Kelola kategori paket, harga, durasi layanan, highlight, visibilitas, dan informasi untuk klien.",
    newPackage: "Paket Baru",
    packageCategories: "Kategori paket",
    backToPackages: "Kembali ke Paket",
    editPackage: "Edit Paket",
    createPackage: "Buat Paket",
    editPackageDescription: "Perbarui informasi yang dilihat klien dan ketersediaan paket ini.",
    createPackageDescription: "Buat paket yang dapat ditampilkan pada halaman booking klien.",
    noPackageCategory: "Tidak ada kategori paket. Isi koleksi PackageCategories terlebih dahulu.",
    packageCategory: "Kategori Paket",
    inactiveCategory: "Kategori Tidak Aktif",
    packageName: "Nama Paket",
    description: "Deskripsi",
    packageDescriptionPlaceholder: "Jelaskan singkat paket dan siapa yang sesuai menggunakannya.",
    bookingSubject: "Subjek Booking",
    bookingSubjectDescription: "Menentukan apakah formulir booking perlu meminta nama pasangan.",
    individualSingle: "Individual / Tunggal",
    individualDescription: "Untuk ulang tahun, sunatan, acara personal, dan paket yang tidak memerlukan pasangan.",
    couplePartnered: "Couple / Berpasangan",
    coupleDescription: "Untuk prewedding, wedding, engagement, dan paket berpasangan lainnya.",
    serviceHighlights: "Highlight Layanan",
    maximumHighlights: "Maksimal enam highlight tercapai",
    typeHighlight: "Ketik highlight lalu tekan Enter",
    highlightHelp: "Tekan Enter untuk membuat badge. Tekan Backspace pada input kosong untuk menghapus badge terakhir.",
    basePrice: "Harga Dasar",
    coverageDuration: "Durasi Layanan",
    displayOrder: "Urutan Tampilan",
    availability: "Ketersediaan",
    active: "Aktif",
    inactive: "Tidak Aktif",
    archived: "Diarsipkan",
    mostPopular: "Paling Populer",
    popularLabelDescription: "Tampilkan label populer pada kartu paket klien.",
    packageCover: "Cover Paket",
    publicImageDescription: "Gunakan URL gambar publik sampai Firebase Storage diterapkan.",
    coverUrl: "URL Cover",
    alternativeText: "Teks Alternatif",
    noCoverImage: "Belum ada gambar cover",
    removeCover: "Hapus cover",
    crewManagement: "Manajemen Kru",
    crewManagementDescription: "Kelola anggota studio, role, status kerja, dan penugasan kru.",
    newCrewMember: "Anggota Kru Baru",
    crewSummary: "Ringkasan Kru",
    studioCrew: "Kru Studio",
    studioCrewDescription: "Klik ikon titik tiga untuk melihat detail kru, mengubah role, status, dan penugasan.",
    member: "Anggota",
    role: "Role",
    contact: "Kontak",
    details: "Detail",
    assigned: "Ditugaskan",
    unavailable: "Tidak Tersedia",
    bookingPreparation: "Persiapan Booking",
    bookingDetail: "Detail Booking",
    bookingDetailDescription: "Lihat snapshot booking, kru yang ditugaskan, invoice, aktivitas pembayaran, dan siapkan invoice pelunasan setelah verifikasi DP.",
    backToBookings: "Kembali ke Daftar Booking",
    loadingBookingDetails: "Memuat detail booking...",
    failedToLoadBookingDetail: "Gagal memuat detail booking",
    bookingNotFound: "Booking tidak ditemukan",
    preparationDescription: "Tinjau booking, konfirmasi kru produksi, lalu siapkan penagihan. Data Firestore hanya diperbarui setelah konfirmasi akhir.",
    preparationProgress: "Progress Persiapan",
    stepsCompleted: "langkah selesai",
    review: "Review",
    crew: "Kru",
    billing: "Penagihan",
    confirmReview: "Konfirmasi Review",
    editReview: "Edit Review",
    reviewConfirmedCrewUnlocked: "Review dikonfirmasi. Pemilihan kru sekarang terbuka.",
    confirmBookingReviewed: "Konfirmasi bahwa seluruh informasi booking sudah ditinjau.",
    crewAssignmentLocked: "Pemilihan kru terkunci",
    confirmReviewUnlockCrew: "Konfirmasi review booking untuk membuka pemilihan kru.",
    confirmCrew: "Konfirmasi Kru",
    editCrew: "Edit Kru",
    crewConfirmedBillingUnlocked: "Kru dikonfirmasi. Persiapan penagihan sekarang terbuka.",
    confirmProductionTeam: "Konfirmasi tim produksi yang dipilih.",
    billingPreparationLocked: "Persiapan penagihan terkunci",
    confirmCrewUnlockBilling: "Konfirmasi penugasan kru untuk membuka persiapan penagihan.",
    confirmBillingGeneratePdf: "Konfirmasi Penagihan & Buat PDF",
    editBilling: "Edit Penagihan",
    confirmBillingDescription: "Konfirmasi penagihan untuk membuat pratinjau PDF invoice DP.",
    generatingPdf: "Membuat PDF...",
    finalStep: "Langkah Terakhir",
    finalConfirmation: "Konfirmasi Akhir",
    stepConfirmed: "Langkah dikonfirmasi",
    confirmationRequired: "Konfirmasi diperlukan",
    processing: "Memproses...",
    bookingReviewConfirmed: "Review booking dikonfirmasi",
    crewAssignmentConfirmed: "Penugasan kru dikonfirmasi",
    depositInvoiceDraftConfirmed: "Draft invoice DP dikonfirmasi",
    depositInvoiceGenerated: "PDF invoice DP dibuat",
    depositInvoiceReviewed: "PDF invoice DP ditinjau",
    reviewBookingTitle: "Tinjau Booking",
    reviewBookingDescription: "Tinjau snapshot klien, acara, lokasi, dan paket terbaru sebelum menugaskan kru.",
    paymentActivity: "Aktivitas Pembayaran",
    paymentActivityDescription: "Pengajuan pembayaran klien untuk booking ini.",
    noPaymentActivity: "Belum ada aktivitas pembayaran",
    noPaymentActivityDescription: "Pengajuan pembayaran klien akan muncul di sini.",
    clientInformation: "Informasi Klien",
    partnerName: "Nama Pasangan",
    phone: "Telepon",
    eventInformation: "Informasi Acara",
    preferredDate: "Tanggal Pilihan",
    location: "Lokasi",
    creativeVision: "Visi Kreatif",
    packageInformation: "Informasi Paket",
    subject: "Subjek",
    duration: "Durasi",
    features: "Fitur",
    bookingSummary: "Ringkasan Booking",
    submitted: "Dikirim",
    estimatedBookingTotal: "Perkiraan Total Booking",
    reviewUnlocksCrew: "Konfirmasi review hanya membuka langkah kru. Tidak ada perubahan Firestore sampai Konfirmasi Akhir.",
    readOnlyBooking: "Booking ini ditampilkan dalam mode hanya baca.",
    crewAssignmentTitle: "Penugasan Kru",
    crewAssignmentDescription: "Semua kru ditampilkan. Hanya kru aktif tanpa penugasan lain pada tanggal tersebut yang dapat dipilih.",
    viewAssignedCrew: "Lihat kru produksi yang ditugaskan untuk booking ini.",
    addFreelance: "Tambah Freelance",
    crewSelectionLocked: "Pemilihan kru terkunci",
    crewSelectionUnlock: "Konfirmasi review booking untuk membuka pemilihan kru.",
    crewSelectionConfirmed: "Pemilihan kru dikonfirmasi",
    editCrewSelection: "Pilih Edit Kru di bawah untuk mengubah pilihan lokal.",
    findCrew: "Cari Kru",
    searchCrew: "Cari kru...",
    filterRole: "Filter Role",
    allRoles: "Semua Role",
    activeCrew: "Kru Aktif",
    busy: "Sibuk",
    assignedLabel: "Ditugaskan",
    availabilityDaily: "Ketersediaan saat ini diperiksa per hari, bukan per jam.",
    assignmentReadOnly: "Penugasan ini ditampilkan dalam mode hanya baca.",
    finalizing: "Menyelesaikan...",
    finalizeApprove: "Selesaikan & Setujui",
    finalConfirmationDescription: "Tindakan ini menyimpan hasil persiapan, mengunggah PDF invoice DP yang telah ditinjau, menerbitkan invoice, mengubah status booking menjadi disetujui, dan mengirim email persetujuan dengan lampiran PDF.",
    billingPayment: "Penagihan & Pembayaran",
    billingPaymentDescription: "Tinjau total booking terbaru, invoice yang diterbitkan, dan aktivitas pembayaran klien.",
    noInvoices: "Belum Ada Invoice",
    noInvoiceDescription: "Belum ada invoice yang tersimpan untuk booking ini.",
    billingPreparation: "Persiapan Penagihan",
    billingPreparationDescription: "Siapkan invoice DP dari snapshot paket dan biaya perjalanan terbaru. Konfirmasi Penagihan membuat pratinjau PDF dari server; tidak ada data yang disimpan sampai Selesaikan & Setujui.",
    createDepositDraftDescription: "Buat draft deposit lokal berdasarkan total booking saat ini. Data ini belum disimpan ke Firestore.",
    createDepositDraft: "Buat Draft Deposit",
    draft: "Draft",
    issued: "Diterbitkan",
    paid: "Lunas",
    overdue: "Jatuh Tempo",
    voidStatus: "Dibatalkan",
    unpaid: "Belum Dibayar",
    pendingVerification: "Menunggu Verifikasi",
    rejected: "Ditolak",
    refunded: "Dikembalikan",
    finalInvoiceTitle: "Invoice Pelunasan",
    finalInvoiceDescription: "DP sudah terverifikasi. Siapkan invoice kedua untuk sisa pembayaran, review PDF, lalu kirim ke klien.",
    travel: "Perjalanan",
    remainingPayment: "Pelunasan",
    createFinalInvoiceDraft: "Buat Draft Invoice Pelunasan",
    invoiceAmount: "Jumlah",
    invoiceNote: "Catatan Invoice",
    amountLockedDescription: "Nominal dikunci dari Total Booking dikurangi pembayaran terverifikasi.",
    pdfCreatedReview: "PDF sudah dibuat. Tinjau sebelum invoice diterbitkan.",
    draftLocal: "Draft masih lokal dan belum mengubah Firestore.",
    generatedDocument: "Dokumen Dibuat",
    hidePreview: "Sembunyikan Pratinjau",
    reviewAgain: "Tinjau Lagi",
    reviewPdf: "Tinjau PDF",
    reviewInvoiceData: "Tinjau total, DP terbayar, sisa pelunasan, dan data klien.",
    download: "Unduh",
    issueSendFinalInvoice: "Terbitkan & Kirim Invoice Pelunasan",
    invoiceDraftConfirmed: "Draft invoice dikonfirmasi",
    pdfGenerated: "PDF dibuat",
    pdfReviewed: "PDF ditinjau",
    issuing: "Menerbitkan...",
  },
  en: {
    home: "Home",
    portfolio: "Portfolio",
    packages: "Packages",
    booking: "Booking",
    login: "Login",
    myAccount: "My Account",
    language: "Language",
    english: "English",
    indonesian: "Bahasa Indonesia",
    nextStep: "Next Step",
    previous: "Previous",
    heroTitle: "Capturing Moments, Creating Memories",
    heroDescription:
      "Every moment has a story, and we capture it with a professional touch and timeless beauty.",
    viewPackages: "View Packages",
    bookNow: "Book Now",
    whyChooseUs: "Why Choose Rafi Picture?",
    qualityPhotos: "QUALITY PHOTOGRAPHY",
    qualityPhotosDescription:
      "Sharp details, thoughtful composition, and natural colors in every photograph.",
    professionalEditing: "PROFESSIONAL EDITING",
    professionalEditingDescription:
      "Every photograph is edited to create a clean, aesthetic, and consistent look.",
    professionalService: "PROFESSIONAL SERVICE",
    professionalServiceDescription:
      "Experienced photographers and a thoughtful process tailored to every client's needs.",
    footerDescription:
      "Photography documentation for weddings, pre-weddings, engagements, and special moments with natural, aesthetic, and distinctive results.",
    contactMessage:
      "Hello Rafi Picture, I would like to ask about your photography services.",
    navigation: "Navigation",
    contactUs: "Contact Us",
    connect: "Connect",
    information: "Information",
    terms: "Terms & Conditions",
    termsDescription:
      "Booking, payment, service duration, and Rafi Picture service policies.",
    copyright: "All rights reserved.",
    welcomeBack: "Welcome Back",
    authLoginDescription:
      "Sign in to access your private gallery and manage your bookings.",
    joinStudio: "Join the Studio",
    authRegisterDescription:
      "Create your account and keep every Rafi Picture moment in one place.",
    signIn: "Sign In",
    createAccount: "Create Account",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    keepSignedIn: "Keep me signed in",
    signingIn: "Signing In...",
    firstName: "First Name",
    lastName: "Last Name",
    createPassword: "Create Password",
    confirmPassword: "Confirm Password",
    sendingVerification: "Sending Verification Code...",
    firstNameLastNameRequired: "First name and last name are required.",
    emailRequired: "Email address is required.",
    passwordMinLength: "Password must contain at least 8 characters.",
    passwordMismatch: "Passwords do not match.",
    verificationFailed: "Unable to send verification code.",
    orContinueWith: "Or continue with",
    firstNamePlaceholder: "Alex",
    lastNamePlaceholder: "Sterling",
    passwordPlaceholder: "Min. 8 characters",
    repeatPasswordPlaceholder: "Repeat password",
    emailPlaceholder: "name@example.com",
    packageFallbackDescription:
      "A photography package that can be tailored to your event and needs.",
    packagesPageTitle: "Our Photography Packages",
    packagesPageDescription:
      "Preserve life's timeless moments through an editorial lens. Choose the package that matches your vision.",
    portfolioPageLabel: "Portfolio",
    portfolioPageTitle: "Stories We Capture",
    portfolioPageDescription:
      "A curated collection of moments from Rafi Picture. Each visit reveals a random selection from our portfolio gallery.",
    bookingPageTitle: "Book Your Session",
    bookingPageDescription:
      "Capture the moments that define the greatest chapters of your life.",
    validPackageRequired: "Please select a valid package.",
    bookingSubmitFailed: "Booking could not be submitted. Please try again.",
    bookingDataUnavailable: "Booking data is unavailable.",
    paymentBookingMismatch: "The payment booking does not match.",
    paymentInvoiceUnavailable: "The payment invoice is invalid or no longer active.",
    depositInvoiceUnavailable: "The deposit invoice is not available yet.",
    finalInvoiceUnavailable: "The final invoice is not available yet.",
    paymentHandlerUnavailable: "The payment submission handler is unavailable.",
    paymentProofRequired: "Please choose a payment proof first.",
    paymentProofUploadFailed: "Payment proof could not be submitted. Please try again.",
    viewDetail: "View Details",
    noPackages: "No packages available",
    popular: "Most Popular",
    packageLabel: "Package",
    startingFrom: "Starting from",
    investmentStartingFrom: "Investment Starting From",
    includedInPackage: "Included in the Package",
    reserveDate: "Reserve Your Date",
    coverage: "Coverage",
    close: "Close",
    termsTitle: "Terms of Agreement",
    termsVersion: "Terms Version",
    termsName: "Terms of Agreement Rafi Picture",
    noPackagesDescription: "Active packages in this category will appear automatically.",
    stepPackages: "Packages",
    stepEventInfo: "Event Info",
    stepPersonalDetails: "Personal Details",
    stepConfirm: "Confirm",
    yourPackagePlan: "Your Package Plan",
    choosePackageDescription: "Choose a documentation package that fits your event and needs.",
    selected: "Selected",
    mostPopular: "Most Popular",
    selectedPackage: "Your selected package",
    changePackage: "Change Package",
    choosePackage: "Choose Package",
    noPackageSelected: "No package selected",
    choosePackageDescriptionShort: "Browse packages by category, price, duration, and available services.",
    packageUnavailable: "The package from the URL was not found or is no longer active. Please choose another package.",
    personalInformation: "Personal Information",
    customerData: "Booking Details",
    personalDescription: "Enter the contact details the Rafi Picture team can use for your booking and event needs.",
    fullName: "Full Name",
    fullNamePlaceholder: "Full name",
    partnerName: "Partner Name",
    partnerNamePlaceholder: "Partner name",
    phoneNumber: "Phone Number",
    phonePlaceholder: "08xxxxxxxxxx",
    optional: "Optional",
    additionalNotes: "Additional Notes",
    tellVision: "Tell Us About Your Vision",
    visionDescription: "Tell us about the concept, atmosphere, or special needs you have in mind. This section is optional.",
    visionPlaceholder: "Example: intimate concept, warm tone, focus on candid family moments...",
    useMyData: "Use My Data",
    next: "Next",
    previousStep: "Previous",
    fullNameRequired: "Full name is required.",
    fullNameMinLength: "Full name must contain at least 2 characters.",
    validEmail: "Please enter a valid email address.",
    phoneRequired: "Phone number is required.",
    validPhone: "Please enter a valid phone number.",
    eventDateRequired: "Event date is required.",
    eventDatePast: "Event date cannot be in the past.",
    startTimeRequired: "Start time is required.",
    venueRequired: "Venue or event location is required.",
    mapLocationRequired: "Choose the event location on the map.",
    packageRequired: "Please select a package.",
    packageUnavailableError: "The selected package is no longer available.",
    packageLoadError: "Packages could not be loaded. Please try again.",
    hoursCoverage: "hours coverage",
    selectedPackages: "Selected Packages",
    addAnotherPackage: "Add Another Package",
    removePackage: "Remove Package",
    categoryLoadError: "Categories could not be loaded. All packages remain available.",
    showing: "Showing",
    eventInformation: "Event Information",
    schedule: "Schedule",
    dateTime: "Date & Time",
    chooseDateDescription: "Choose the event date first. Once selected, choose the event start time.",
    eventDate: "Event Date",
    notSelected: "Not selected",
    changeDate: "Change Date",
    chooseDate: "Choose Date",
    dateAvailable: "The date is available and selected.",
    scheduleLoadError: "Schedule data could not be loaded. Please try again.",
    startTime: "Start Time",
    endTime: "End Time",
    nextDay: "next day",
    chooseStartTime: "Choose a start time",
    packageDurationUnavailable: "Package duration is unavailable",
    packageDuration: "Package duration",
    endTimeDescription: "The end time will be calculated when package duration is available.",
    venue: "Venue",
    eventLocation: "Event Location",
    locationDescription: "Enter a venue name or address. Location search is optional; you can also choose a point directly on the map.",
    venueAddress: "Venue Name / Address",
    venuePlaceholder: "Example: Hotel Savoy Homann Bandung",
    searching: "Searching...",
    searchLocation: "Search Location",
    locationHelp: "The venue name may be any text. The location name and a map point are required.",
    locationFound: "Location found. The map point has been adjusted.",
    mapPoint: "Map Point",
    useMyLocation: "Use my location",
    removePoint: "Remove point",
    waitingLocation: "Waiting for location",
    agencyNotConfigured: "Agency is not configured",
    distanceFrom: "Distance from",
    accommodationCost: "Accommodation Cost",
    accommodationRequest: "Accommodation Request",
    accommodationPolicyShort: "All areas within Bandung City are free of accommodation costs; locations outside the city will incur a charge.",
    bandungAccommodation: "All areas within Bandung City are free of accommodation costs. Locations outside Bandung City incur an accommodation cost.",
    freeDistance: "Free distance applies up to",
    afterDistance: "; after that, a charge of",
    andIncreases: "and increases by",
    eachDistance: "for every",
    distanceStraightLine: "following interval. Distance is calculated as a straight line.",
    confirmation: "Confirmation",
    reviewBooking: "Review Your Booking",
    reviewBookingDescription: "Make sure the package, schedule, location, and contact information are correct before submitting your booking request.",
    beforeSubmitBooking: "Before Sending Your Booking",
    beforeSubmitAvailability: "Submitting the form does not guarantee the event date is available.",
    beforeSubmitReview: "The team will review the schedule, location, and event requirements first.",
    beforeSubmitPrice: "The package price may change if additional requirements are identified.",
    beforeSubmitContact: "The team will contact you through the email address or phone number provided.",
    submittingBooking: "Sending booking request...",
    bookingSentSuccess: "Booking request sent successfully.",
    bookingWillBeReviewed: "Your information has been received and will be reviewed by the team.",
    packageDetails: "Documentation Package",
    selectedPackageDescription: "The package and services selected for this event.",
    includedServices: "Included Services",
    packagePrice: "Package Price",
    subjectCouple: "Couple / partnered",
    subjectIndividual: "Individual",
    subjectUnknown: "Subject type not categorized",
    eventDetails: "Event Details",
    eventDetailsDescription: "Schedule, location, and accommodation cost for this booking.",
    eventTime: "Event Time",
    personalDetails: "Booking Details",
    personalDetailsDescription: "Information the team will use to contact you.",
    visionNotes: "Vision & Notes",
    visionNotesDescription: "Concepts or additional needs you would like to share with the team.",
    eventNotes: "Event Notes",
    accommodationPolicy: "All areas within Bandung City are free of accommodation costs. Locations outside Bandung City incur an accommodation cost. Free distance applies up to",
    all: "All",
    categoryWedding: "Wedding",
    categoryPreWedding: "Pre-Wedding",
    categoryEngagement: "Engagement",
    categoryEvent: "Event",
    categoryBundle: "Bundle",
    bookingDataUnavailable: "Booking data is unavailable.",
    statusPendingLabel: "Pending Review",
    statusPendingTitle: "Inquiry Sent Successfully",
    statusPendingDescription: "Your booking request has been received. The Rafi Picture team will review the schedule, location, package, and event requirements first.",
    statusApprovedLabel: "Approved",
    statusApprovedTitle: "Booking Approved",
    statusApprovedDescription: "Your booking request has been approved. Please continue to the deposit payment stage.",
    statusConfirmedLabel: "Payment Submitted",
    statusConfirmedTitle: "Payment Under Review",
    statusConfirmedDescription: "Your payment proof has been received and is being verified by the Rafi Picture admin team.",
    statusInProgressLabel: "In Progress",
    statusInProgressTitle: "Booking In Progress",
    statusInProgressDescription: "Your booking is active and the team is preparing the service according to your event details.",
    statusCompletedLabel: "Completed",
    statusCompletedTitle: "Booking Completed",
    statusCompletedDescription: "Your booking process is complete. Thank you for using Rafi Picture.",
    statusCancelledLabel: "Cancelled",
    statusCancelledTitle: "Booking Cancelled",
    statusCancelledDescription: "This booking has been cancelled. Contact the Rafi Picture team if you need more information.",
    statusFinalPaymentLabel: "Final Payment Submitted",
    statusFinalPaymentTitle: "Final Payment Under Review",
    statusFinalPaymentDescription: "Your final payment proof has been received and is being verified by the Rafi Picture admin team.",
    statusPaidLabel: "Paid in Full",
    statusPaidTitle: "Payment Complete",
    statusPaidDescription: "All booking payments have been verified. The invoice and payment receipt are available in Payment Documents.",
    serviceStatus: "Service status: In Progress",
    bookingCode: "Booking Code",
    submittedAt: "Submitted",
    travelCost: "Travel Cost",
    eventDateLabel: "Event Date",
    eventLocationLabel: "Event Location",
    clientDataDescription: "Contact information the Rafi Picture team will use for booking communication.",
    visionAndNotes: "Vision & Notes",
    visionAndNotesDescription: "Concepts or additional needs shared during booking.",
    costSummary: "Cost Summary",
    costSummaryDescription: "This summary is based on the package and travel cost recorded when the inquiry was submitted.",
    sendingBooking: "Sending...",
    inquirySent: "Inquiry Sent",
    sendInquiry: "Send Inquiry",
    paymentDocuments: "Payment Documents",
    paymentDocumentsDescription: "Invoices and receipts issued for this booking.",
    finalAmountNotice: "The final amount will follow the admin review and invoice issued after the booking is approved.",
    lastUpdated: "Last updated",
    nextDay: "next day",
    depositInvoice: "Deposit Invoice",
    finalInvoice: "Final Payment Invoice",
    paymentReceipt: "Payment Receipt",
    fullPayment: "100% Payment",
    adminDashboard: "Dashboard",
    adminSchedules: "Schedules",
    adminCrewManagement: "Crew Management",
    adminOrders: "Orders",
    adminPackageManagement: "Package Management",
    adminPayments: "Payments",
    adminStudio: "Studio Admin",
    changePhoto: "Change Photo",
    loggingOut: "Logging out...",
    logout: "Logout",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    adminOverview: "Overview",
    dashboard: "Dashboard",
    dashboardDescription: "Live summary from bookings, crew schedules, and payments.",
    totalOrders: "Total Orders",
    upcomingSchedules: "Upcoming Schedules",
    monthlyRevenue: "Monthly Revenue",
    pendingPayments: "Pending Payments",
    verified: "Verified",
    pending: "Pending",
    failedToLoadDashboard: "Failed to load dashboard",
    dashboardDataUnavailable: "Booking, assignment, or payment data could not be loaded.",
    report: "Report",
    bookingReport: "Booking Report",
    reportPeriod: "Report Period",
    downloadReport: "Download Report",
    totalRevenue: "Total Revenue",
    totalClients: "Total Clients",
    mostSelectedPackage: "Most Selected Package",
    selections: "Selections",
    package: "Package",
    monthlyBookings: "Monthly Bookings",
    monthlyBookingsDescription: "Booking requests submitted during the last six months.",
    lastMonths: "Last 6 months",
    paymentDistribution: "Payment Distribution",
    paymentDistributionDescription: "Verified and pending payments this month.",
    fulfilled: "Fulfilled",
    latestBookings: "Latest Bookings",
    latestBookingsDescription: "Most recently submitted booking requests.",
    viewAll: "View All",
    noBookingsYet: "No bookings yet",
    newBookingsAppear: "New booking requests will appear here after clients submit the booking form.",
    billingAndPayments: "Billing & Payments",
    manageYourPayment: "Manage Your Payment",
    completeDepositUpload: "Complete the deposit payment and upload your transfer proof to continue the booking.",
    completeFinalUpload: "Complete the final payment and upload your transfer proof to settle the booking payment.",
    paymentStatus: "Status",
    transactionSuccessful: "Successful",
    awaitingPayment: "Awaiting Payment",
    awaitingVerification: "Awaiting Verification",
    paymentVerified: "Payment Verified",
    paymentComplete: "Completed",
    cancelledStatus: "Cancelled",
    finalPaymentWaiting: "Awaiting Final Payment",
    transactionHistory: "Transaction History",
    noTransactions: "No transactions yet",
    transactionHistoryEmpty: "Payment history will appear after transfer proof is submitted.",
    reference: "Reference",
    method: "Method",
    quantity: "Amount",
    remainingDue: "Remaining Amount Due",
    downloadReceipt: "Download Receipt",
    bankTransfer: "Bank Transfer",
    copied: "Copied",
    copy: "Copy",
    paymentProofSent: "Payment Proof Submitted",
    paymentProofReview: "The admin is reviewing your transfer proof. Upload will be available again if the payment is rejected.",
    uploadUnavailable: "Upload Unavailable",
    uploadOnlyApproved: "Transfer proof can only be submitted after the booking has been approved.",
    paymentProof: "Payment Proof",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    towardEventDay: "Countdown to Event Day",
    eventDayArrived: "The event day has arrived",
    eventCountdown: "Event countdown",
    live: "Live",
    eventStartReached: "The event start time has arrived. Booking status details continue to follow Rafi Picture's operational process.",
    eventStarts: "Event starts",
    timerFrozen: "Timer Frozen",
    overdue: "Overdue",
    paymentDeadline: "Payment Deadline",
    previousProofRejected: "Previous proof rejected",
    adminDeadline: "Admin deadline",
    issuedDate: "Issued Date",
    invoiceLabel: "Invoice",
    servicePackage: "Service Package",
    totalCost: "Total Cost",
    depositDue: "Deposit Due",
    finalPaymentDue: "Final Payment Due",
    invoiceFile: "Invoice File",
    depositInvoiceLabel: "Deposit Invoice",
    finalInvoiceLabel: "Final Payment Invoice",
    viewPdf: "View PDF",
    depositVerifiedNotice: "Your booking will be secured after the admin verifies the deposit payment. Keep the transfer proof until verification is complete.",
    finalVerifiedNotice: "After the final payment is verified, the system will issue a 100% payment receipt and send it by email.",
    paymentDeadlineDescription: "Complete the payment and submit your transfer proof before the deadline set by the admin.",
    uploadPaymentProof: "Upload Payment Proof",
    clickOrDropUpload: "Click to upload or drag and drop",
    imageRequirements: "PNG, JPG, or JPEG - maximum 5 MB",
    removeFile: "Remove file",
    sendingPaymentProof: "Sending Payment Proof...",
    confirmPaymentProof: "Confirm Payment Proof",
    selectProofToEnable: "The confirmation button becomes active after a payment proof photo is selected.",
    copiedAccountError: "The account number could not be copied.",
    frozenOverdueDescription: "The overdue timer was frozen when payment proof was submitted and will resume from the same position if the proof is rejected by the admin.",
    frozenDescription: "The countdown is frozen while submitted payment proof is awaiting admin verification.",
    overdueDescription: "The deadline has passed. The overdue timer continues until new payment proof is submitted.",
    timerFrozen: "Timer Frozen",
    previousProofRejected: "Previous proof rejected",
    adminDeadline: "Admin deadline",
    bookings: "Bookings",
    bookingManagement: "Booking Management",
    bookingManagementDescription: "Review incoming booking requests, monitor their status, and manage photography orders.",
    bookingSummary: "Booking summary",
    bookingFilters: "Booking filters",
    searchClientPackageLocation: "Search client, package, or location...",
    filterBookingStatus: "Filter booking status",
    allStatuses: "All Statuses",
    advancedFilters: "Advanced filters",
    downloadData: "Download data",
    client: "Client",
    eventDate: "Event Date",
    amount: "Amount",
    status: "Status",
    action: "Action",
    pendingReview: "Pending Review",
    approvedAwaitingPayment: "Approved · Awaiting Payment",
    paymentUnderReview: "Payment Under Review",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    paymentsPage: "Payments",
    paymentManagement: "Payment Management",
    paymentManagementDescription: "Review payment proofs and manage booking transaction statuses.",
    paymentFilters: "Payment filters",
    searchPayment: "Search payment...",
    allPayments: "All Payments",
    newestFirst: "Newest First",
    oldestFirst: "Oldest First",
    noPaymentsFound: "No payments found",
    noPaymentsFoundDescription: "Client payment submissions will appear here after a proof has been uploaded.",
    reviewPayment: "Review payment",
    verificationDetail: "Verification Detail",
    rejected: "Rejected",
    schedule: "Schedule",
    scheduleManagement: "Schedule Management",
    scheduleManagementDescription: "View booking requests awaiting review and active schedules after deposit payment verification.",
    loadingScheduleData: "Loading schedule data...",
    failedLoadScheduleData: "Failed to load booking or schedule data.",
    showAll: "Show All",
    showBookings: "Show Bookings",
    showSchedules: "Show Scheduled",
    crew: "Crew",
    totalCrew: "Total Crew",
    available: "Available",
    currentlyAssigned: "Currently Assigned",
    upcomingAssignments: "Upcoming Assignments",
    packageManagement: "Package Management",
    packageManagementDescription: "Manage package categories, pricing, service duration, highlights, visibility, and client-facing information.",
    newPackage: "New Package",
    packageCategories: "Package categories",
    backToPackages: "Back to Packages",
    editPackage: "Edit Package",
    createPackage: "Create Package",
    editPackageDescription: "Update the client-facing information and availability of this package.",
    createPackageDescription: "Create a package that can be displayed on the client booking page.",
    noPackageCategory: "No package category is available. Seed the PackageCategories collection first.",
    packageCategory: "Package Category",
    inactiveCategory: "Inactive category",
    packageName: "Package Name",
    description: "Description",
    packageDescriptionPlaceholder: "Briefly explain the package and who it is suitable for.",
    bookingSubject: "Booking Subject",
    bookingSubjectDescription: "Controls whether the client booking form should ask for a partner name.",
    individualSingle: "Individual / Single",
    individualDescription: "For birthday, circumcision, personal events, and packages that do not require a partner.",
    couplePartnered: "Couple / Partnered",
    coupleDescription: "For prewedding, wedding, engagement, and other paired packages.",
    serviceHighlights: "Service Highlights",
    maximumHighlights: "Maximum of six highlights reached",
    typeHighlight: "Type a highlight and press Enter",
    highlightHelp: "Press Enter to create a badge. Press Backspace on an empty input to remove the last badge.",
    basePrice: "Base Price",
    coverageDuration: "Coverage Duration",
    displayOrder: "Display Order",
    availability: "Availability",
    active: "Active",
    inactive: "Inactive",
    archived: "Archived",
    mostPopular: "Most Popular",
    popularLabelDescription: "Show the popular label on the client package card.",
    packageCover: "Package Cover",
    publicImageDescription: "Use a public image URL until Firebase Storage is implemented.",
    coverUrl: "Cover URL",
    alternativeText: "Alternative Text",
    noCoverImage: "No cover image",
    removeCover: "Remove cover",
    crewManagement: "Crew Management",
    crewManagementDescription: "Manage studio members, roles, work status, and crew assignments.",
    newCrewMember: "New Crew Member",
    crewSummary: "Crew summary",
    studioCrew: "Studio Crew",
    studioCrewDescription: "Click the three-dot icon to view crew details and edit roles, status, and assignments.",
    member: "Member",
    role: "Role",
    contact: "Contact",
    details: "Details",
    assigned: "Assigned",
    unavailable: "Unavailable",
    bookingPreparation: "Booking Preparation",
    bookingDetail: "Booking Detail",
    bookingDetailDescription: "View the booking snapshot, assigned crew, invoices, payment activity, and prepare the final settlement invoice after DP verification.",
    backToBookings: "Back to Bookings",
    loadingBookingDetails: "Loading booking details...",
    failedToLoadBookingDetail: "Failed to load booking detail",
    bookingNotFound: "Booking not found",
    preparationDescription: "Review the booking, confirm the production crew, then prepare billing. Firestore is updated only after Final Confirmation.",
    preparationProgress: "Preparation Progress",
    stepsCompleted: "steps completed",
    review: "Review",
    crew: "Crew",
    billing: "Billing",
    confirmReview: "Confirm Review",
    editReview: "Edit Review",
    reviewConfirmedCrewUnlocked: "Review confirmed locally. Crew assignment is now unlocked.",
    confirmBookingReviewed: "Confirm that all booking information has been reviewed.",
    crewAssignmentLocked: "Crew assignment is locked",
    confirmReviewUnlockCrew: "Confirm the booking review to unlock crew assignment.",
    confirmCrew: "Confirm Crew",
    editCrew: "Edit Crew",
    crewConfirmedBillingUnlocked: "Crew confirmed locally. Billing preparation is now unlocked.",
    confirmProductionTeam: "Confirm the selected production team.",
    billingPreparationLocked: "Billing preparation is locked",
    confirmCrewUnlockBilling: "Confirm the crew assignment to unlock billing preparation.",
    confirmBillingGeneratePdf: "Confirm Billing & Generate PDF",
    editBilling: "Edit Billing",
    confirmBillingDescription: "Confirm billing to generate the DP invoice PDF preview.",
    generatingPdf: "Generating PDF...",
    finalStep: "Final Step",
    finalConfirmation: "Final Confirmation",
    stepConfirmed: "Step confirmed",
    confirmationRequired: "Confirmation required",
    processing: "Processing...",
    bookingReviewConfirmed: "Booking review confirmed",
    crewAssignmentConfirmed: "Crew assignment confirmed",
    depositInvoiceDraftConfirmed: "Deposit invoice draft confirmed",
    depositInvoiceGenerated: "Deposit invoice PDF generated",
    depositInvoiceReviewed: "Deposit invoice PDF reviewed",
    reviewBookingTitle: "Review Booking",
    reviewBookingDescription: "Review the latest client, event, location, and package snapshot before assigning the crew.",
    paymentActivity: "Payment Activity",
    paymentActivityDescription: "Client payment submissions for this booking.",
    noPaymentActivity: "No payment activity",
    noPaymentActivityDescription: "Client payment submissions will appear here.",
    clientInformation: "Client Information",
    partnerName: "Partner Name",
    phone: "Phone",
    eventInformation: "Event Information",
    preferredDate: "Preferred Date",
    location: "Location",
    creativeVision: "Creative Vision",
    packageInformation: "Package Information",
    subject: "Subject",
    duration: "Duration",
    features: "Features",
    bookingSummary: "Booking Summary",
    submitted: "Submitted",
    estimatedBookingTotal: "Estimated Booking Total",
    reviewUnlocksCrew: "Confirming this review only unlocks the crew step. No Firestore changes are made until Final Confirmation.",
    readOnlyBooking: "This booking is displayed in read-only mode.",
    crewAssignmentTitle: "Crew Assignment",
    crewAssignmentDescription: "All crew are shown. Only active crew without another assignment on the selected date can be selected.",
    viewAssignedCrew: "View the production crew assigned to this booking.",
    addFreelance: "Add Freelance",
    crewSelectionLocked: "Crew assignment is locked",
    crewSelectionUnlock: "Confirm the booking review to unlock crew selection.",
    crewSelectionConfirmed: "Crew selection confirmed",
    editCrewSelection: "Choose Edit Crew below to change the local selection.",
    findCrew: "Find Crew",
    searchCrew: "Search crew...",
    filterRole: "Filter Role",
    allRoles: "All Roles",
    activeCrew: "Active Crew",
    busy: "Busy",
    assignedLabel: "Assigned",
    availabilityDaily: "Availability is currently checked per day, not per hour.",
    assignmentReadOnly: "This assignment is displayed in read-only mode.",
    finalizing: "Finalizing...",
    finalizeApprove: "Finalize & Approve",
    finalConfirmationDescription: "This is the only action that persists the preparation result, uploads the reviewed DP invoice PDF, issues the invoice, changes the booking status to approved, and sends the approval email with the PDF attached.",
    billingPayment: "Billing & Payment",
    billingPaymentDescription: "Review the latest booking total, issued invoices, and client payment activity.",
    noInvoices: "No invoices",
    noInvoiceDescription: "No invoice has been saved for this booking.",
    billingPreparation: "Billing Preparation",
    billingPreparationDescription: "Prepare the deposit invoice from the latest package and travel-charge snapshot. Confirm Billing generates a server-side PDF preview first; nothing is saved until Finalize & Approve.",
    createDepositDraftDescription: "Create a local deposit draft based on the current booking total. This does not write anything to Firestore.",
    createDepositDraft: "Create Deposit Draft",
    draft: "Draft",
    issued: "Issued",
    paid: "Paid",
    overdue: "Overdue",
    voidStatus: "Void",
    unpaid: "Unpaid",
    pendingVerification: "Pending Verification",
    rejected: "Rejected",
    refunded: "Refunded",
    finalInvoiceTitle: "Final Settlement Invoice",
    finalInvoiceDescription: "The deposit has been verified. Prepare the second invoice for the remaining payment, review the PDF, then send it to the client.",
    travel: "Travel",
    remainingPayment: "Remaining Payment",
    createFinalInvoiceDraft: "Create Final Invoice Draft",
    invoiceAmount: "Amount",
    invoiceNote: "Invoice Note",
    amountLockedDescription: "Amount is locked from Booking Total minus verified payments.",
    pdfCreatedReview: "PDF created. Review it before issuing the invoice.",
    draftLocal: "Draft is local and has not changed Firestore.",
    generatedDocument: "Generated Document",
    hidePreview: "Hide Preview",
    reviewAgain: "Review Again",
    reviewPdf: "Review PDF",
    reviewInvoiceData: "Review total, paid deposit, remaining payment, and client data.",
    download: "Download",
    issueSendFinalInvoice: "Issue & Send Final Invoice",
    invoiceDraftConfirmed: "Invoice draft confirmed",
    pdfGenerated: "PDF generated",
    pdfReviewed: "PDF reviewed",
    issuing: "Issuing...",
  },
};

const LanguageContext = createContext(null);

const languageListeners = new Set();

function normalizeLanguage(value) {
  return value === "en" ? "en" : DEFAULT_LANGUAGE;
}

function subscribeToLanguage(callback) {
  languageListeners.add(callback);

  if (typeof window === "undefined") {
    return () => languageListeners.delete(callback);
  }

  const handleStorageChange = (event) => {
    if (event.key === STORAGE_KEY) callback();
  };

  window.addEventListener("storage", handleStorageChange);

  return () => {
    languageListeners.delete(callback);
    window.removeEventListener("storage", handleStorageChange);
  };
}

function getStoredLanguage() {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;

  return normalizeLanguage(window.localStorage.getItem(STORAGE_KEY));
}

function getServerLanguage() {
  return DEFAULT_LANGUAGE;
}

export default function LanguageProvider({ children }) {
  const language = useSyncExternalStore(
    subscribeToLanguage,
    getStoredLanguage,
    getServerLanguage,
  );

  function setLanguage(nextLanguage) {
    const normalizedLanguage = normalizeLanguage(nextLanguage);
    window.localStorage.setItem(STORAGE_KEY, normalizedLanguage);
    languageListeners.forEach((listener) => listener());
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      translate: (key) => translations[language][key] ?? key,
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}
